name: kern3l
run-name: kernel

on:
  push:
    branches: [ rebase ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nexgang/ubuntu:latest

    steps:
      - uses: actions/checkout@v4
      - name: Nexus Kernel Alioth
        run: bash build_kernel.sh
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
